#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

eval 'use MemcachedPP';
die "It looks like you don't have the MemcachedPP installed." if $@;

MemcachedPP->start;
